import { type StudyQuestion } from "./study-game.functions";

export interface SubjectTopic {
  id: string;
  name: string;
  summary: string;
  explanation: string;
  keyPoints: string[];
  examples?: string[];
  presetQuestions: StudyQuestion[];
}

export interface SchoolSubject {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
  badgeColor: string;
  bgLight: string;
  borderColor: string;
  topics: SubjectTopic[];
}

export const SCHOOL_SUBJECTS: SchoolSubject[] = [
  // ==========================================
  // 1. ➗ MATEMÁTICAS
  // ==========================================
  {
    id: "matematicas",
    name: "Matemáticas",
    icon: "➗",
    description: "Números, álgebra, ecuaciones y problemas.",
    color: "text-blue-600 dark:text-blue-400",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    bgLight: "from-blue-500/10 to-indigo-500/5",
    borderColor: "border-blue-200 dark:border-blue-800/80",
    topics: [
      {
        id: "operaciones-basicas",
        name: "Operaciones básicas y jerarquía",
        summary: "Suma, resta, multiplicación, división y orden de operaciones (PEMDAS).",
        explanation:
          "Las operaciones básicas siguen un orden estricto llamado Jerarquía de Operaciones (PEMDAS). Primero se resuelven los paréntesis (), luego potencias y raíces, después multiplicaciones y divisiones de izquierda a derecha, y al final sumas y restas de izquierda a derecha.\n\nRegla de los signos: Signos iguales multiplicados dan positivo (+ × + = + y - × - = +), mientras que signos diferentes dan negativo (+ × - = -). Cualquier número multiplicado por cero es igual a 0.",
        keyPoints: [
          "Jerarquía PEMDAS: 1° Paréntesis, 2° Potencias, 3° Multiplicación y División, 4° Suma y Resta.",
          "Las multiplicaciones se resuelven ANTES que las sumas externas.",
          "Signos iguales multiplicados resultan en positivo: (-6) × (-4) = +24.",
          "Cualquier número multiplicado por cero es igual a 0 (a × 0 = 0).",
          "Ejemplo de multiplicación directa: 8 × 7 = 56.",
        ],
        examples: ["5 + 4 × 3 = 5 + 12 = 17 (primero la multiplicación)", "(-6) × (-4) = 24", "8 × 7 = 56"],
        presetQuestions: [
          {
            id: "mat_op_1",
            type: "multiple_choice",
            concept: "Jerarquía de Operaciones",
            question: "Según la explicación, ¿cuál es el resultado de la operación 5 + 4 × 3?",
            options: ["12", "17", "27", "20"],
            correctAnswer: "17",
            correctIndex: 1,
            explanation: "¿Por qué? Como explica el texto, primero se resuelve la multiplicación (4 × 3 = 12) y luego la suma (5 + 12 = 17).",
          },
          {
            id: "mat_op_2",
            type: "multiple_choice",
            concept: "Multiplicación de Signos Iguales",
            question: "Según la regla de los signos explicada, ¿cuál es el resultado de (-6) × (-4)?",
            options: ["-24", "-10", "24", "10"],
            correctAnswer: "24",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica que signos iguales multiplicados dan positivo (- × - = +), por lo que (-6) × (-4) = 24.",
          },
          {
            id: "mat_op_3",
            type: "fill_blank",
            concept: "Multiplicación por Cero",
            question: "Según el texto, cualquier número multiplicado por cero es igual a ________.",
            options: ["1", "infinito", "el mismo número", "0"],
            correctAnswer: "0",
            correctIndex: 3,
            explanation: "¿Por qué? La explicación señala textualmente que cualquier número multiplicado por cero es igual a 0.",
          },
          {
            id: "mat_op_4",
            type: "true_false",
            concept: "Prioridad en la Jerarquía",
            question: "En la jerarquía PEMDAS explicada, las sumas se resuelven antes que las operaciones dentro de los paréntesis.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El primer paso de la jerarquía PEMDAS son los paréntesis; las sumas externas van al final.",
          },
          {
            id: "mat_op_5",
            type: "multiple_choice",
            concept: "Ejemplo de Multiplicación",
            question: "De acuerdo con los ejemplos del texto, ¿cuánto es 8 × 7?",
            options: ["56", "54", "64", "48"],
            correctAnswer: "56",
            correctIndex: 0,
            explanation: "¿Por qué? El texto indica en los puntos clave que 8 × 7 = 56.",
          },
        ],
      },
      {
        id: "fracciones",
        name: "Fracciones",
        summary: "Numerador, denominador, suma homogénea, multiplicación y división.",
        explanation:
          "Una fracción representa partes de una unidad. El numerador (número de arriba) indica cuántas partes tomamos, y el denominador (número de abajo) indica el total de partes iguales en que se dividió la unidad.\n\nOperaciones con fracciones:\n- Suma con mismo denominador: Se suman directamente los numeradores y se conserva intacto el denominador (ejemplo: 3/8 + 2/8 = 5/8; nunca se suman los denominadores).\n- Multiplicación: Se multiplican numeradores entre sí y denominadores entre sí en línea recta (ejemplo: 2/5 × 3/4 = 6/20 o 3/10).\n- División: Se multiplica en cruz (ejemplo: 1/3 ÷ 2/5 = (1×5)/(3×2) = 5/6).\n- Simplificación: La fracción 2/4 dividida entre 2 equivale a 1/2.",
        keyPoints: [
          "Numerador (arriba) = partes que se toman; Denominador (abajo) = total de partes divididas.",
          "Suma homogénea: 3/8 + 2/8 = 5/8 (se mantiene el denominador intacto, no se suma 8+8).",
          "Multiplicación en línea recta: (2/5) × (3/4) = 6/20 (simplificado 3/10).",
          "División en cruz: (1/3) ÷ (2/5) = 5/6.",
          "Simplificación: 2/4 equivale a 1/2.",
        ],
        examples: ["(2/5) × (3/4) = 6/20 = 3/10", "3/8 + 2/8 = 5/8", "(1/3) ÷ (2/5) = 5/6", "2/4 = 1/2"],
        presetQuestions: [
          {
            id: "mat_frac_1",
            type: "multiple_choice",
            concept: "Multiplicación de Fracciones",
            question: "Según la explicación, ¿cuál es el resultado de (2/5) × (3/4)?",
            options: ["5/9", "6/20 (o 3/10)", "8/15", "6/9"],
            correctAnswer: "6/20 (o 3/10)",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación indica que se multiplica en línea recta: 2 × 3 = 6 (arriba) y 5 × 4 = 20 (abajo), resultando en 6/20 (o 3/10).",
          },
          {
            id: "mat_frac_2",
            type: "multiple_choice",
            concept: "Suma con Mismo Denominador",
            question: "De acuerdo con el texto, ¿cuánto es 3/8 + 2/8?",
            options: ["5/16", "6/8", "5/8", "6/16"],
            correctAnswer: "5/8",
            correctIndex: 2,
            explanation: "¿Por qué? Al tener el mismo denominador, el texto explica que se suman numeradores (3 + 2 = 5) y se conserva el 8.",
          },
          {
            id: "mat_frac_3",
            type: "true_false",
            concept: "Regla de Suma de Fracciones",
            question: "Según la explicación, al sumar fracciones con el mismo denominador también se deben sumar los denominadores entre sí.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto aclara que el denominador se conserva intacto y solo se suman los numeradores.",
          },
          {
            id: "mat_frac_4",
            type: "fill_blank",
            concept: "Simplificación",
            question: "Según la explicación, la fracción 2/4 simplificada equivale a ________.",
            options: ["1/4", "3/4", "1/2", "2/2"],
            correctAnswer: "1/2",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación menciona textualmente que 2/4 simplificado es 1/2.",
          },
          {
            id: "mat_frac_5",
            type: "multiple_choice",
            concept: "División en Cruz",
            question: "Según la explicación, ¿cuál es el resultado de (1/3) ÷ (2/5)?",
            options: ["5/6", "2/15", "3/10", "6/5"],
            correctAnswer: "5/6",
            correctIndex: 0,
            explanation: "¿Por qué? Como explica el texto, al multiplicar en cruz se obtiene 1 × 5 = 5 (numerador) y 3 × 2 = 6 (denominador), dando 5/6.",
          },
        ],
      },
      {
        id: "porcentajes",
        name: "Porcentajes",
        summary: "Concepto de tanto por ciento, cálculo del 50%, 25%, 20% y 10%.",
        explanation:
          "El porcentaje representa una cantidad de cada 100 partes. Calcular el 100% de un número representa la totalidad del número.\n\nCálculos clave explicados:\n- El 50% equivale a la mitad exacta de una cantidad (dividir entre 2). Ejemplo: el 50% de $200 es $100.\n- El 25% equivale a una cuarta parte (multiplicar por 0.25).\n- El 20% de una cantidad se obtiene multiplicando por 0.20. Ejemplo: el 20% de 150 es 30.\n- El 10% se calcula recorriendo el punto un lugar o dividiendo entre 10. Ejemplo: el 10% de 480 es 48.",
        keyPoints: [
          "El 100% representa la totalidad del número.",
          "El 50% es la mitad exacta: el 50% de $200 es $100.",
          "El 25% equivale a multiplicar por el decimal 0.25.",
          "El 20% de 150 es igual a 30 (150 × 0.20 = 30).",
          "El 10% de 480 es 48 (dividir 480 entre 10).",
        ],
        examples: ["50% de $200 = $100", "20% de 150 = 30", "10% de 480 = 48", "25% = × 0.25"],
        presetQuestions: [
          {
            id: "mat_pct_1",
            type: "multiple_choice",
            concept: "Cálculo del 20%",
            question: "Según el texto, ¿cuánto es el 20% de 150?",
            options: ["20", "25", "15", "30"],
            correctAnswer: "30",
            correctIndex: 3,
            explanation: "¿Por qué? La explicación indica expresamente que el 20% de 150 es 30 (150 × 0.20 = 30).",
          },
          {
            id: "mat_pct_2",
            type: "multiple_choice",
            concept: "Cálculo del 50%",
            question: "Según el ejemplo del texto, si una playera cuesta $200 y tiene 50% de descuento, ¿cuál es su costo?",
            options: ["$150", "$100", "$50", "$80"],
            correctAnswer: "$100",
            correctIndex: 1,
            explanation: "¿Por qué? El texto explica que el 50% de $200 es exactamente la mitad, es decir, $100.",
          },
          {
            id: "mat_pct_3",
            type: "true_false",
            concept: "Definición del 50%",
            question: "Según el texto, calcular el 50% de una cantidad equivale a duplicar o triplicar el valor.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto explica que el 50% representa la mitad exacta de una cantidad.",
          },
          {
            id: "mat_pct_4",
            type: "fill_blank",
            concept: "Definición del 100%",
            question: "Según el texto, el 100% de cualquier número representa ________.",
            options: ["cero", "la totalidad del número", "el doble", "la mitad"],
            correctAnswer: "la totalidad del número",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación afirma que el 100% representa la totalidad del número.",
          },
          {
            id: "mat_pct_5",
            type: "multiple_choice",
            concept: "Cálculo del 10%",
            question: "De acuerdo con la explicación, ¿cuánto es el 10% de 480?",
            options: ["4.8", "480", "48", "24"],
            correctAnswer: "48",
            correctIndex: 2,
            explanation: "¿Por qué? El texto explica que el 10% se calcula dividiendo entre 10, dando 48.",
          },
        ],
      },
      {
        id: "algebra",
        name: "Álgebra y Ecuaciones",
        summary: "Variables, términos semejantes y despeje de incógnitas (x).",
        explanation:
          "El álgebra utiliza letras llamadas variables o incógnitas para representar números desconocidos (como la letra 'x').\n\nReglas clave explicadas:\n- Términos semejantes: Se pueden sumar o restar si tienen la misma letra (ejemplo: 4x + 7x - 2x = 9x).\n- Despeje de ecuaciones: Si un término está sumando a la izquierda, pasa al lado derecho restando. Si está restando, pasa sumando. Si está multiplicando, pasa dividiendo.\n- En la ecuación 2x + 4 = 14: el 4 pasa restando (2x = 10) y el 2 pasa dividiendo (x = 5).\n- En la ecuación x - 8 = 12: el 8 pasa sumando (x = 12 + 8 = 20).",
        keyPoints: [
          "La letra 'x' en 3x + 5 se llama variable o incógnita.",
          "Términos semejantes: 4x + 7x - 2x = 9x.",
          "Regla de despeje: Un término sumando en la izquierda pasa a la derecha restando.",
          "Ecuación 2x + 4 = 14 → x = 5.",
          "Ecuación x - 8 = 12 → x = 20.",
        ],
        examples: ["2x + 4 = 14 → x = 5", "x - 8 = 12 → x = 20", "4x + 7x - 2x = 9x"],
        presetQuestions: [
          {
            id: "mat_alg_1",
            type: "multiple_choice",
            concept: "Resolución de Ecuación",
            question: "Según el ejemplo del texto, en la ecuación 2x + 4 = 14, ¿cuál es el valor de x?",
            options: ["7", "9", "4", "5"],
            correctAnswer: "5",
            correctIndex: 3,
            explanation: "¿Por qué? Como explica el texto: 2x = 14 - 4 = 10, luego x = 10 / 2 = 5.",
          },
          {
            id: "mat_alg_2",
            type: "multiple_choice",
            concept: "Suma de Términos Semejantes",
            question: "De acuerdo con el texto, ¿cuál es el resultado de simplificar 4x + 7x - 2x?",
            options: ["9x", "13x", "9x²", "11x"],
            correctAnswer: "9x",
            correctIndex: 0,
            explanation: "¿Por qué? La explicación muestra que 4 + 7 = 11, y 11 - 2 = 9x.",
          },
          {
            id: "mat_alg_3",
            type: "true_false",
            concept: "Regla de Despeje Falsa",
            question: "Según el texto, si un término está sumando en el lado izquierdo de una ecuación, pasa al lado derecho sumando el doble.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La regla de despeje explicada en el texto indica que lo que está sumando pasa al otro lado restando.",
          },
          {
            id: "mat_alg_4",
            type: "fill_blank",
            concept: "Definición de Variable",
            question: "Según el texto, la letra que representa un número desconocido en una expresión algebraica se llama ________.",
            options: ["denominador", "variable o incógnita", "constante fija", "exponente"],
            correctAnswer: "variable o incógnita",
            correctIndex: 1,
            explanation: "¿Por qué? El texto define a las letras como variables o incógnitas.",
          },
          {
            id: "mat_alg_5",
            type: "multiple_choice",
            concept: "Despeje con Resta",
            question: "Según el ejemplo del texto, si x - 8 = 12, ¿cuánto vale x?",
            options: ["4", "20", "96", "-4"],
            correctAnswer: "20",
            correctIndex: 1,
            explanation: "¿Por qué? Como indica el texto, el 8 pasa sumando: x = 12 + 8 = 20.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 2. 🧪 QUÍMICA
  // ==========================================
  {
    id: "quimica",
    name: "Química",
    icon: "🧪",
    description: "Materia, elementos, reacciones y conceptos químicos.",
    color: "text-emerald-600 dark:text-emerald-400",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    bgLight: "from-emerald-500/10 to-teal-500/5",
    borderColor: "border-emerald-200 dark:border-emerald-800/80",
    topics: [
      {
        id: "materia-mezclas",
        name: "Materia, estados y mezclas",
        summary: "Estados de agregación, cambios de fase y mezclas homogéneas y heterogéneas.",
        explanation:
          "La materia es todo lo que ocupa un lugar en el espacio. Se presenta en tres estados principales:\n- Sólido, Líquido y Gaseoso (los gases no tienen volumen ni forma fijos, sino que se expanden ocupando todo el recipiente).\n\nCambios de estado explicados:\n- Fusión: Paso de sólido a líquido al absorber calor.\n- Condensación: Paso de gas o vapor a líquido al enfriarse.\n\nTipos de mezclas explicados:\n- Mezcla homogénea: Sus componentes forman una sola fase uniforme y no se distinguen a simple vista (ejemplo: agua con sal completamente disuelta).\n- Mezcla heterogénea: Se distinguen dos o más fases claramente (ejemplo: agua y aceite, porque no se mezclan y forman capas separadas).",
        keyPoints: [
          "Mezcla homogénea: Forma una sola fase uniforme (ejemplo: agua con sal disuelta).",
          "Mezcla heterogénea: Se distinguen dos o más fases (ejemplo: agua y aceite).",
          "Fusión: Cambio de estado de sólido a líquido.",
          "Condensación: Cambio de estado de gas/vapor a líquido.",
          "Los gases no tienen forma ni volumen fijos; se expanden en el recipiente.",
        ],
        examples: ["Agua con sal = Mezcla homogénea", "Agua con aceite = Mezcla heterogénea", "Hielo derritiéndose = Fusión"],
        presetQuestions: [
          {
            id: "qui_mat_1",
            type: "multiple_choice",
            concept: "Mezcla Homogénea",
            question: "Según la explicación, ¿cuál es un ejemplo de mezcla homogénea?",
            options: ["Agua con aceite", "Ensalada de frutas", "Agua con sal completamente disuelta", "Arena con piedras"],
            correctAnswer: "Agua con sal completamente disuelta",
            correctIndex: 2,
            explanation: "¿Por qué? El texto menciona textualmente que el agua con sal bien disuelta es un ejemplo de mezcla homogénea.",
          },
          {
            id: "qui_mat_2",
            type: "multiple_choice",
            concept: "Cambio de Estado: Fusión",
            question: "De acuerdo con el texto, ¿cómo se llama el cambio de estado de sólido a líquido?",
            options: ["Evaporación", "Fusión", "Condensación", "Sublimación"],
            correctAnswer: "Fusión",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación define la fusión como el paso de sólido a líquido.",
          },
          {
            id: "qui_mat_3",
            type: "true_false",
            concept: "Propiedades de los Gases",
            question: "Según el texto, los gases tienen volumen y forma fijos que no se adaptan al recipiente.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto aclara que los gases NO tienen forma ni volumen fijos, sino que se expanden en el recipiente.",
          },
          {
            id: "qui_mat_4",
            type: "fill_blank",
            concept: "Condensación",
            question: "Según la explicación, el paso de gas o vapor a líquido se conoce como ________.",
            options: ["solidificación", "combustión", "fusión", "condensación"],
            correctAnswer: "condensación",
            correctIndex: 3,
            explanation: "¿Por qué? El texto define la condensación como el paso de gas a líquido.",
          },
          {
            id: "qui_mat_5",
            type: "multiple_choice",
            concept: "Mezcla Heterogénea",
            question: "Según el texto, ¿por qué el agua y el aceite forman una mezcla heterogénea?",
            options: [
              "Porque no se mezclan y se pueden distinguir dos fases claramente",
              "Porque forman una sola sustancia pura transparente",
              "Porque ambos son metales pesados",
              "Porque reaccionan produciendo fuego",
            ],
            correctAnswer: "Porque no se mezclan y se pueden distinguir dos fases claramente",
            correctIndex: 0,
            explanation: "¿Por qué? La explicación indica que el agua y el aceite forman capas separadas distinguibles.",
          },
        ],
      },
      {
        id: "tabla-periodica",
        name: "Tabla periódica y estructura del átomo",
        summary: "Protones, electrones, neutrones, número atómico y símbolos químicos.",
        explanation:
          "El átomo está compuesto por:\n- Protones: Partículas con carga eléctrica positiva ubicadas en el núcleo.\n- Neutrones: Partículas sin carga eléctrica ubicadas también en el núcleo.\n- Electrones: Partículas con carga eléctrica negativa que orbitan alrededor del núcleo.\n\nConceptos clave de la tabla periódica explicados:\n- Número atómico: Indica la cantidad de protones que tiene un átomo en su núcleo.\n- Símbolo químico del Oxígeno: Se representa con la letra mayúscula 'O'.\n- Molécula de agua (H₂O): Está formada por exactamente 2 átomos de hidrógeno y 1 átomo de oxígeno.",
        keyPoints: [
          "Protones: Carga eléctrica positiva en el núcleo.",
          "Electrones: Carga eléctrica negativa orbitando alrededor del núcleo.",
          "Número atómico: Cantidad de protones en el núcleo del elemento.",
          "El símbolo químico del Oxígeno es 'O'.",
          "La molécula de agua (H₂O) tiene 2 átomos de hidrógeno.",
        ],
        examples: ["Protones (+)", "Electrones (-)", "Símbolo del Oxígeno = O", "Fórmula del agua = H2O"],
        presetQuestions: [
          {
            id: "qui_tab_1",
            type: "multiple_choice",
            concept: "Protones",
            question: "Según el texto, ¿qué partículas con carga positiva se encuentran en el núcleo del átomo?",
            options: ["Los electrones", "Los protones", "Los neutrones", "Los fotones"],
            correctAnswer: "Los protones",
            correctIndex: 1,
            explanation: "¿Por qué? El texto señala expresamente que los protones tienen carga positiva y se ubican en el núcleo.",
          },
          {
            id: "qui_tab_2",
            type: "multiple_choice",
            concept: "Símbolo del Oxígeno",
            question: "De acuerdo con la explicación, ¿cuál es el símbolo químico del Oxígeno?",
            options: ["Ox", "Om", "O", "Og"],
            correctAnswer: "O",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica textualmente que el símbolo químico del Oxígeno es la letra 'O'.",
          },
          {
            id: "qui_tab_3",
            type: "true_false",
            concept: "Carga de Protones Falsa",
            question: "Según la explicación, los protones poseen carga eléctrica negativa.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto aclara que los protones tienen carga positiva; los electrones son los que tienen carga negativa.",
          },
          {
            id: "qui_tab_4",
            type: "fill_blank",
            concept: "Número Atómico",
            question: "Según el texto, el número atómico de un elemento indica la cantidad de ________ en su núcleo.",
            options: ["electrones de valencia", "neutrones", "protones", "moléculas"],
            correctAnswer: "protones",
            correctIndex: 2,
            explanation: "¿Por qué? El texto define el número atómico como la cantidad de protones en el núcleo.",
          },
          {
            id: "qui_tab_5",
            type: "multiple_choice",
            concept: "Átomos en el Agua",
            question: "Según el texto, ¿cuántos átomos de hidrógeno tiene una molécula de agua (H₂O)?",
            options: ["1", "2", "3", "0"],
            correctAnswer: "2",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación indica textualmente que el agua (H₂O) tiene 2 átomos de hidrógeno.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 3. 🇬🇧 INGLÉS
  // ==========================================
  {
    id: "ingles",
    name: "Inglés",
    icon: "🇬🇧",
    description: "Gramática, vocabulario y comprensión.",
    color: "text-rose-600 dark:text-rose-400",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    bgLight: "from-rose-500/10 to-red-500/5",
    borderColor: "border-rose-200 dark:border-rose-800/80",
    topics: [
      {
        id: "verb-to-be",
        name: "Verb To Be & Pronouns",
        summary: "Uso de am, is, are y pronombres personales (I, you, he, she, it, we, they).",
        explanation:
          "En inglés, el verbo 'to be' significa 'ser' o 'estar'.\n\nReglas de conjugación explicadas:\n- Con el pronombre 'I' (yo) se utiliza 'am' (ejemplo: I am a student = Yo soy estudiante).\n- Con la tercera persona singular ('He', 'She', 'It') se utiliza 'is' (ejemplo: She is my best friend = Ella es mi mejor amiga).\n- Con los pronombres plurales ('You', 'We', 'They') se utiliza 'are' (ejemplo: They are playing soccer = Ellos están jugando fútbol).\n- El pronombre 'it' se usa para referirse a objetos o animales en singular.\n- La contracción negativa de 'is not' es 'isn't'.",
        keyPoints: [
          "'I am' se utiliza para decir 'Yo soy' o 'Yo estoy'.",
          "Con 'She' se usa 'is': 'She is my best friend'.",
          "Con 'They' se usa 'are': 'They are playing soccer'.",
          "El pronombre 'it' se utiliza para cosas o animales.",
          "La contracción de 'is not' es 'isn't'.",
        ],
        examples: ["I am", "She is", "They are", "is not → isn't"],
        presetQuestions: [
          {
            id: "eng_be_1",
            type: "multiple_choice",
            concept: "Conjugación con She",
            question: "Según la regla explicada, ¿cuál es la opción correcta para: 'She ________ my best friend'?",
            options: ["are", "am", "is", "be"],
            correctAnswer: "is",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica que con 'She' se utiliza la forma 'is'.",
          },
          {
            id: "eng_be_2",
            type: "multiple_choice",
            concept: "Conjugación con They",
            question: "Según la regla explicada, ¿cuál es la opción correcta para: 'They ________ playing soccer'?",
            options: ["are", "is", "am", "was"],
            correctAnswer: "are",
            correctIndex: 0,
            explanation: "¿Por qué? El texto explica que con el pronombre plural 'They' se usa 'are'.",
          },
          {
            id: "eng_be_3",
            type: "true_false",
            concept: "Conjugación She am Falsa",
            question: "Según la regla explicada, con el pronombre 'She' se debe conjugar con 'am'.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La regla indica que con 'She' se usa 'is'; 'am' se usa exclusivamente con 'I'.",
          },
          {
            id: "eng_be_4",
            type: "fill_blank",
            concept: "Pronombre It",
            question: "Según el texto, el pronombre en inglés para referirse a un objeto o animal es ________.",
            options: ["he", "it", "they", "we"],
            correctAnswer: "it",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación indica expresamente que 'it' se utiliza para objetos y animales.",
          },
          {
            id: "eng_be_5",
            type: "multiple_choice",
            concept: "Contracción isn't",
            question: "De acuerdo con el texto, ¿cuál es la contracción negativa correcta de 'is not'?",
            options: ["aren't", "amn't", "don't", "isn't"],
            correctAnswer: "isn't",
            correctIndex: 3,
            explanation: "¿Por qué? La explicación menciona textualmente que 'is not' se contrae como 'isn't'.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 4. 📜 HISTORIA
  // ==========================================
  {
    id: "historia",
    name: "Historia",
    icon: "📜",
    description: "Civilizaciones, acontecimientos y personajes históricos.",
    color: "text-amber-700 dark:text-amber-400",
    badgeColor: "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/20",
    bgLight: "from-amber-500/10 to-yellow-500/5",
    borderColor: "border-amber-200 dark:border-amber-800/80",
    topics: [
      {
        id: "civilizaciones-antiguas",
        name: "Civilizaciones antiguas",
        summary: "Mesopotamia, Egipto, Grecia y Roma.",
        explanation:
          "Las primeras grandes civilizaciones de la antigüedad se desarrollaron junto a ríos y mares:\n- Mesopotamia: Significa 'tierra entre dos ríos' porque se ubicó entre los ríos Tigris y Éufrates, y desarrolló la escritura cuneiforme.\n- Egipto: Floreció junto al río Nilo, cuyas crecidas dejaban limo fértil para la agricultura.\n- Grecia: En la ciudad de Atenas nació la democracia como sistema de gobierno donde los ciudadanos votaban.\n- Roma: Su mayor legado a la sociedad moderna fue el Derecho romano y las bases de las leyes actuales.",
        keyPoints: [
          "Mesopotamia se ubicó entre los ríos Tigris y Éufrates.",
          "La escritura cuneiforme fue desarrollada en Mesopotamia.",
          "Egipto dependía de las aguas y crecidas del río Nilo para su agricultura.",
          "En la ciudad griega de Atenas nació la democracia.",
          "El gran legado de Roma a la sociedad moderna fue el Derecho romano.",
        ],
        examples: ["Ríos Tigris y Éufrates", "Escritura cuneiforme", "Democracia en Atenas", "Derecho romano"],
        presetQuestions: [
          {
            id: "his_civ_1",
            type: "multiple_choice",
            concept: "Ríos de Mesopotamia",
            question: "Según el texto, ¿qué ríos alimentaban los valles de la antigua Mesopotamia?",
            options: ["Nilo y Amazonas", "Tigris y Éufrates", "Ganges e Indo", "Rin y Danubio"],
            correctAnswer: "Tigris y Éufrates",
            correctIndex: 1,
            explanation: "¿Por qué? El texto indica textualmente que Mesopotamia se ubicó entre los ríos Tigris y Éufrates.",
          },
          {
            id: "his_civ_2",
            type: "multiple_choice",
            concept: "Nacimiento de la Democracia",
            question: "De acuerdo con el texto, ¿qué sistema de gobierno nació en la antigua ciudad de Atenas (Grecia)?",
            options: ["La monarquía absoluta", "El feudalismo", "La democracia", "La dictadura militar"],
            correctAnswer: "La democracia",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación menciona que en Atenas nació la democracia como sistema donde los ciudadanos votaban.",
          },
          {
            id: "his_civ_3",
            type: "true_false",
            concept: "Escritura Cuneiforme Falsa",
            question: "Según el texto, la escritura cuneiforme fue inventada originalmente en la civilización de Roma.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La explicación señala expresamente que la escritura cuneiforme fue desarrollada en Mesopotamia.",
          },
          {
            id: "his_civ_4",
            type: "fill_blank",
            concept: "Escritura Cuneiforme",
            question: "Según el texto, la escritura desarrollada en Mesopotamia se llama ________.",
            options: ["jeroglífica", "alfabeto latino", "griega", "cuneiforme"],
            correctAnswer: "cuneiforme",
            correctIndex: 3,
            explanation: "¿Por qué? La explicación señala que Mesopotamia desarrolló la escritura cuneiforme.",
          },
          {
            id: "his_civ_5",
            type: "multiple_choice",
            concept: "Legado de Roma",
            question: "Según la explicación, ¿cuál fue uno de los principales legados de Roma a la sociedad moderna?",
            options: ["El Derecho y las bases de las leyes actuales", "La brújula magnética", "La invención del papel", "El ábaco"],
            correctAnswer: "El Derecho y las bases de las leyes actuales",
            correctIndex: 0,
            explanation: "¿Por qué? El texto indica textualmente que el gran legado de Roma fue el Derecho romano y las leyes.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 5. 🧬 BIOLOGÍA
  // ==========================================
  {
    id: "biologia",
    name: "Biología",
    icon: "🧬",
    description: "Seres vivos, células, genética y sistemas.",
    color: "text-emerald-700 dark:text-emerald-400",
    badgeColor: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/20",
    bgLight: "from-emerald-500/10 to-green-500/5",
    borderColor: "border-emerald-200 dark:border-emerald-800/80",
    topics: [
      {
        id: "la-celula",
        name: "La célula y organelos",
        summary: "Estructura celular, procariotas, eucariotas, mitocondria y fotosíntesis.",
        explanation:
          "La célula es la unidad anatómica y funcional básica de todos los seres vivos. Según la Teoría Celular, todos los seres vivos están formados por una o más células.\n\nEstructuras y funciones explicadas:\n- Núcleo: Organelo que alberga el ADN y dirige todas las actividades celulares.\n- Mitocondria: Organelo encargado de generar energía (ATP) a través de la respiración celular.\n- Células vegetales: Poseen una pared celular de celulosa que les da rigidez y soporte, y cloroplastos donde ocurre la fotosíntesis.\n- Células animales: Carecen de pared celular y de cloroplastos.",
        keyPoints: [
          "Todos los seres vivos están formados por una o más células (Teoría Celular).",
          "El núcleo contiene el ADN y dirige la actividad celular.",
          "La mitocondria produce energía (ATP) mediante la respiración celular.",
          "La pared celular de celulosa da rigidez exclusiva a las células vegetales.",
          "Los cloroplastos son los organelos donde ocurre la fotosíntesis en plantas.",
        ],
        examples: ["Núcleo = ADN", "Mitocondria = ATP / Energía", "Cloroplastos = Fotosíntesis", "Pared celular = Soporte vegetal"],
        presetQuestions: [
          {
            id: "bio_cel_1",
            type: "multiple_choice",
            concept: "Función de la Mitocondria",
            question: "Según el texto, ¿cuál es la función principal de la mitocondria?",
            options: [
              "Sintetizar la pared de celulosa",
              "Generar energía (ATP) a través de la respiración celular",
              "Almacenar el material genético de los virus",
              "Realizar la fotosíntesis con luz solar",
            ],
            correctAnswer: "Generar energía (ATP) a través de la respiración celular",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación señala textualmente que la mitocondria genera energía (ATP) mediante la respiración celular.",
          },
          {
            id: "bio_cel_2",
            type: "multiple_choice",
            concept: "Pared Celular Vegetal",
            question: "De acuerdo con el texto, ¿qué estructura otorga rigidez y soporte a las células vegetales?",
            options: ["La membrana plasmática", "El citoplasma", "La pared celular de celulosa", "El lisosoma"],
            correctAnswer: "La pared celular de celulosa",
            correctIndex: 2,
            explanation: "¿Por qué? El texto explica que la pared celular de celulosa da rigidez y soporte a las células vegetales.",
          },
          {
            id: "bio_cel_3",
            type: "true_false",
            concept: "Cloroplastos Animales Falsos",
            question: "Según la explicación, las células animales poseen cloroplastos para realizar la fotosíntesis.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto señala textualmente que las células animales carecen de cloroplastos; solo las células vegetales los tienen.",
          },
          {
            id: "bio_cel_4",
            type: "fill_blank",
            concept: "Función del Núcleo",
            question: "Según el texto, el organelo que alberga el ADN y dirige la actividad celular es el ________.",
            options: ["ribosoma", "retículo", "flagelo", "núcleo"],
            correctAnswer: "núcleo",
            correctIndex: 3,
            explanation: "¿Por qué? El texto indica que el núcleo contiene el ADN y coordina las funciones celulares.",
          },
          {
            id: "bio_cel_5",
            type: "multiple_choice",
            concept: "Cloroplastos y Fotosíntesis",
            question: "Según la explicación, ¿en qué organelo vegetal ocurre la fotosíntesis?",
            options: ["En los cloroplastos", "En las mitocondrias", "En el aparato de Golgi", "En los centriolos"],
            correctAnswer: "En los cloroplastos",
            correctIndex: 0,
            explanation: "¿Por qué? La explicación señala expresamente que en los cloroplastos ocurre la fotosíntesis.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 6. 📖 ESPAÑOL
  // ==========================================
  {
    id: "espanol",
    name: "Español",
    icon: "📖",
    description: "Gramática, lectura, literatura y escritura.",
    color: "text-purple-600 dark:text-purple-400",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    bgLight: "from-purple-500/10 to-indigo-500/5",
    borderColor: "border-purple-200 dark:border-purple-800/80",
    topics: [
      {
        id: "ortografia-acentuacion",
        name: "Acentuación y ortografía",
        summary: "Sílaba tónica, palabras agudas, graves y esdrújulas.",
        explanation:
          "La sílaba tónica es aquella que se pronuncia con mayor intensidad o fuerza de voz en una palabra.\n\nClasificación y reglas de acentuación explicadas:\n- Palabras Agudas: Tienen la sílaba tónica en la última sílaba y llevan tilde cuando terminan en N, S o Vocal (ejemplo: 'corazón' termina en N).\n- Palabras Graves: Tienen la sílaba tónica en la penúltima sílaba y llevan tilde cuando terminan en consonantes distintas a N o S (ejemplo: 'árbol' termina en L).\n- Palabras Esdrújulas: Tienen la sílaba tónica en la antepenúltima sílaba y SIEMPRE llevan tilde sin excepción (ejemplo: 'música').",
        keyPoints: [
          "La sílaba tónica concentra la mayor fuerza de voz de la palabra.",
          "Las palabras agudas llevan tilde si terminan en N, S o Vocal.",
          "La palabra 'corazón' es aguda porque termina en N y suena en la última sílaba.",
          "La palabra 'árbol' es grave y lleva tilde porque termina en L (no N ni S).",
          "Las palabras esdrújulas (como 'música') siempre llevan tilde.",
        ],
        examples: ["Música = Esdrújula (siempre con tilde)", "Corazón = Aguda (termina en N)", "Árbol = Grave (termina en L)"],
        presetQuestions: [
          {
            id: "esp_ort_1",
            type: "multiple_choice",
            concept: "Palabra Esdrújula",
            question: "Según la explicación, ¿cuál de las siguientes palabras es esdrújula y siempre lleva tilde?",
            options: ["Canción", "Música", "Reloj", "Papel"],
            correctAnswer: "Música",
            correctIndex: 1,
            explanation: "¿Por qué? El texto señala que 'música' es esdrújula y las esdrújulas siempre llevan tilde.",
          },
          {
            id: "esp_ort_2",
            type: "multiple_choice",
            concept: "Regla de Agudas",
            question: "De acuerdo con el texto, ¿cuándo llevan tilde las palabras agudas?",
            options: [
              "Cuando terminan en cualquier consonante excepto N o S",
              "Siempre, sin excepción",
              "Cuando terminan en N, S o Vocal",
              "Nunca llevan tilde",
            ],
            correctAnswer: "Cuando terminan en N, S o Vocal",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica expresamente que las agudas se acentúan cuando terminan en N, S o vocal.",
          },
          {
            id: "esp_ort_3",
            type: "true_false",
            concept: "Tilde en Esdrújulas",
            question: "Según el texto, las palabras esdrújulas nunca llevan tilde.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La explicación aclara que las palabras esdrújulas SIEMPRE llevan tilde sin excepción.",
          },
          {
            id: "esp_ort_4",
            type: "fill_blank",
            concept: "Definición de Sílaba Tónica",
            question: "Según el texto, la sílaba que se pronuncia con mayor intensidad en una palabra es la sílaba ________.",
            options: ["átona", "diptongo", "hiato", "tónica"],
            correctAnswer: "tónica",
            correctIndex: 3,
            explanation: "¿Por qué? El texto define a la sílaba tónica como la de mayor fuerza de pronunciación.",
          },
          {
            id: "esp_ort_5",
            type: "multiple_choice",
            concept: "Clasificación de Corazón",
            question: "Según el ejemplo de la explicación, ¿qué tipo de palabra es 'corazón'?",
            options: ["Aguda", "Grave", "Esdrújula", "Sobreesdrújula"],
            correctAnswer: "Aguda",
            correctIndex: 0,
            explanation: "¿Por qué? El texto explica que 'corazón' es aguda porque termina en N.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 7. 🌎 GEOGRAFÍA
  // ==========================================
  {
    id: "geografia",
    name: "Geografía",
    icon: "🌎",
    description: "Países, mapas, clima y territorio.",
    color: "text-cyan-600 dark:text-cyan-400",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    bgLight: "from-cyan-500/10 to-sky-500/5",
    borderColor: "border-cyan-200 dark:border-cyan-800/80",
    topics: [
      {
        id: "continentes-oceanos",
        name: "Continentes y océanos",
        summary: "Proporción de agua, océanos, continentes y líneas imaginarias.",
        explanation:
          "Datos geográficos del planeta Tierra explicados:\n- Proporción de agua: Aproximadamente el 70% de la superficie de la Tierra está cubierta por agua.\n- Océano más grande: El Océano Pacífico es el más extenso del planeta.\n- Continente más grande y poblado: Asia es el continente con mayor territorio y población.\n- Línea del Ecuador: Es la línea imaginaria que divide la Tierra en Hemisferio Norte y Hemisferio Sur.\n- Montaña más alta: El monte Everest se ubica en la cordillera del Himalaya, en el continente de Asia.",
        keyPoints: [
          "Aproximadamente el 70% del planeta está cubierto por agua.",
          "El Océano Pacífico es el más grande del mundo.",
          "Asia es el continente más grande y poblado.",
          "La línea del Ecuador divide a la Tierra en Hemisferio Norte y Hemisferio Sur.",
          "El monte Everest se encuentra en la cordillera del Himalaya (Asia).",
        ],
        examples: ["70% agua", "Pacífico = Océano mayor", "Ecuador = Divide Norte y Sur", "Everest = Himalaya (Asia)"],
        presetQuestions: [
          {
            id: "geo_con_1",
            type: "multiple_choice",
            concept: "Océano Pacífico",
            question: "Según el texto, ¿cuál es el océano más grande del planeta Tierra?",
            options: ["Océano Atlántico", "Océano Pacífico", "Océano Índico", "Océano Ártico"],
            correctAnswer: "Océano Pacífico",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación afirma que el Océano Pacífico es el más extenso del planeta.",
          },
          {
            id: "geo_con_2",
            type: "multiple_choice",
            concept: "Línea del Ecuador",
            question: "De acuerdo con el texto, ¿qué línea imaginaria divide la Tierra en Hemisferio Norte y Hemisferio Sur?",
            options: ["El Meridiano de Greenwich", "El Trópico de Cáncer", "El Ecuador", "El Círculo Polar"],
            correctAnswer: "El Ecuador",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica expresamente que el Ecuador divide la Tierra en hemisferios Norte y Sur.",
          },
          {
            id: "geo_con_3",
            type: "true_false",
            concept: "Cobertura de Agua Falsa",
            question: "Según el texto, el 70% de la superficie de la Tierra está cubierta por tierra firme y desiertos.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. El texto indica que aproximadamente el 70% de la superficie está cubierta por agua.",
          },
          {
            id: "geo_con_4",
            type: "fill_blank",
            concept: "Cobertura de Agua",
            question: "Según la explicación, aproximadamente el ________% de la superficie de la Tierra está cubierta por agua.",
            options: ["30", "50", "95", "70"],
            correctAnswer: "70",
            correctIndex: 3,
            explanation: "¿Por qué? El texto indica textualmente que el 70% de la superficie terrestre está cubierta por agua.",
          },
          {
            id: "geo_con_5",
            type: "multiple_choice",
            concept: "Ubicación del Everest",
            question: "Según la explicación, ¿en qué cordillera y continente se encuentra el monte Everest?",
            options: ["El Himalaya (Asia)", "Los Andes (América)", "Los Alpes (Europa)", "Rocosas (América)"],
            correctAnswer: "El Himalaya (Asia)",
            correctIndex: 0,
            explanation: "¿Por qué? La explicación señala textualmente que el monte Everest está en la cordillera del Himalaya, en Asia.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 8. 💻 INFORMÁTICA
  // ==========================================
  {
    id: "informatica",
    name: "Informática",
    icon: "💻",
    description: "Tecnología, programación y conceptos digitales.",
    color: "text-indigo-600 dark:text-indigo-400",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    bgLight: "from-indigo-500/10 to-violet-500/5",
    borderColor: "border-indigo-200 dark:border-indigo-800/80",
    topics: [
      {
        id: "hardware-software",
        name: "Hardware y software",
        summary: "Componentes físicos, programas, CPU y memoria RAM.",
        explanation:
          "Conceptos fundamentales de computación explicados:\n- Hardware: Corresponde a los componentes físicos y tangibles que se pueden tocar (ejemplo: el teclado físico, la pantalla, el ratón).\n- CPU (Procesador): Es conocido como el 'cerebro' de la computadora porque ejecuta las instrucciones y cálculos.\n- Memoria RAM: Es una memoria temporal que pierde sus datos cuando la computadora se apaga.\n- Software de sistema: Windows, macOS y Linux son ejemplos de sistemas operativos.\n- Almacenamiento digital: 1 Gigabyte (GB) equivale exactamente a 1,024 Megabytes (MB).",
        keyPoints: [
          "El teclado físico es un ejemplo de hardware.",
          "La CPU (Procesador) es el 'cerebro' de la computadora.",
          "La memoria RAM es temporal y pierde la información al apagar el equipo.",
          "Windows, macOS y Linux son sistemas operativos.",
          "1 Gigabyte (GB) = 1,024 Megabytes (MB).",
        ],
        examples: ["Teclado = Hardware", "CPU = Cerebro / Procesador", "RAM = Memoria temporal", "1 GB = 1,024 MB"],
        presetQuestions: [
          {
            id: "inf_hw_1",
            type: "multiple_choice",
            concept: "Ejemplo de Hardware",
            question: "Según el texto, ¿cuál de los siguientes es un ejemplo de hardware?",
            options: ["El sistema operativo Windows", "Un videojuego digital", "El teclado físico", "Un archivo PDF"],
            correctAnswer: "El teclado físico",
            correctIndex: 2,
            explanation: "¿Por qué? El texto señala expresamente al teclado físico como ejemplo de componente de hardware.",
          },
          {
            id: "inf_hw_2",
            type: "multiple_choice",
            concept: "Cerebro CPU",
            question: "De acuerdo con la explicación, ¿qué componente es conocido como el 'cerebro' de la computadora?",
            options: ["La fuente de poder", "La CPU (Procesador)", "El ratón", "El gabinete"],
            correctAnswer: "La CPU (Procesador)",
            correctIndex: 1,
            explanation: "¿Por qué? El texto define a la CPU (Procesador) como el cerebro que ejecuta los cálculos.",
          },
          {
            id: "inf_hw_3",
            type: "true_false",
            concept: "Memoria RAM Permanente Falsa",
            question: "Según la explicación, la memoria RAM almacena información permanentemente incluso al apagar la computadora.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La explicación señala textualmente que la memoria RAM es temporal y pierde sus datos al apagarse.",
          },
          {
            id: "inf_hw_4",
            type: "fill_blank",
            concept: "Sistemas Operativos",
            question: "Según el texto, Windows, macOS y Linux son ejemplos de ________.",
            options: ["dispositivos de almacenamiento", "chips de memoria", "sistemas operativos", "antenas de red"],
            correctAnswer: "sistemas operativos",
            correctIndex: 2,
            explanation: "¿Por qué? El texto clasifica a Windows, macOS y Linux como sistemas operativos.",
          },
          {
            id: "inf_hw_5",
            type: "multiple_choice",
            concept: "Equivalencia 1 GB",
            question: "Según la explicación, ¿cuántos Megabytes (MB) equivalen a 1 Gigabyte (GB)?",
            options: ["100 MB", "10 MB", "1,024 MB", "1,000,000 MB"],
            correctAnswer: "1,024 MB",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación afirma textualmente que 1 GB equivale a 1,024 MB.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 9. ⚡ FÍSICA
  // ==========================================
  {
    id: "fisica",
    name: "Física",
    icon: "⚡",
    description: "Movimiento, fuerza, energía y materia.",
    color: "text-amber-600 dark:text-amber-400",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    bgLight: "from-amber-500/10 to-orange-500/5",
    borderColor: "border-amber-200 dark:border-amber-800/80",
    topics: [
      {
        id: "leyes-newton-fisica",
        name: "Leyes de Newton y movimiento",
        summary: "Inercia, fuerza y masa (F = m·a), acción-reacción y velocidad.",
        explanation:
          "Leyes del movimiento y conceptos de física explicados:\n- Primera Ley (Inercia): Los cuerpos conservan su velocidad o estado de reposo a menos que una fuerza actúe sobre ellos. Por ejemplo, te vas hacia adelante cuando un autobús frena por inercia.\n- Segunda Ley (Fuerza): La fórmula matemática es Fuerza = masa × aceleración (F = m · a).\n- Tercera Ley (Acción y Reacción): A toda acción le corresponde una reacción de igual magnitud en sentido opuesto (ejemplo: un cohete que expulsa gases hacia abajo es impulsado hacia arriba).\n- Unidad de fuerza: En el Sistema Internacional se mide en Newtons (N).\n- Fórmula de velocidad: Velocidad = distancia / tiempo (v = d / t). Si un auto recorre 120 metros en 6 segundos, su velocidad es 120 / 6 = 20 m/s.",
        keyPoints: [
          "Fórmula de la Segunda Ley de Newton: F = m · a.",
          "Velocidad v = d / t: 120 metros en 6 segundos = 20 m/s.",
          "Tercera Ley: A toda acción corresponde una reacción opuesta (cohete impulsado hacia arriba).",
          "La unidad de fuerza en el Sistema Internacional es el Newton (N).",
          "Inercia: Causa por la que el cuerpo se inclina hacia adelante al frenar un autobús.",
        ],
        examples: ["F = m · a", "v = 120 m / 6 s = 20 m/s", "Fuerza = Newtons (N)", "Cohete = Acción y Reacción"],
        presetQuestions: [
          {
            id: "fis_new_1",
            type: "multiple_choice",
            concept: "Fórmula de Fuerza",
            question: "Según el texto, ¿cuál es la fórmula matemática de la Segunda Ley de Newton?",
            options: ["E = m · c²", "F = m · a", "v = d / t", "W = F / d"],
            correctAnswer: "F = m · a",
            correctIndex: 1,
            explanation: "¿Por qué? La explicación indica expresamente que la fórmula es Fuerza = masa × aceleración (F = m · a).",
          },
          {
            id: "fis_new_2",
            type: "multiple_choice",
            concept: "Cálculo de Velocidad",
            question: "De acuerdo con el ejemplo del texto, si un automóvil recorre 120 metros en 6 segundos, ¿cuál es su velocidad?",
            options: ["720 m/s", "12 m/s", "60 m/s", "20 m/s"],
            correctAnswer: "20 m/s",
            correctIndex: 3,
            explanation: "¿Por qué? El texto explica que v = d / t: 120 metros / 6 segundos = 20 m/s.",
          },
          {
            id: "fis_new_3",
            type: "true_false",
            concept: "Fórmula de Newton Falsa",
            question: "Según el texto, la fórmula de la Segunda Ley de Newton es Fuerza = masa dividida entre aceleración (F = m / a).",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Es Falso. La fórmula indicada en el texto es Fuerza = masa multiplicada por aceleración (F = m · a).",
          },
          {
            id: "fis_new_4",
            type: "fill_blank",
            concept: "Unidad de Medida",
            question: "Según la explicación, la unidad de medida de la fuerza en el Sistema Internacional es el ________.",
            options: ["Joule (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)"],
            correctAnswer: "Newton (N)",
            correctIndex: 1,
            explanation: "¿Por qué? El texto señala expresamente que la fuerza se mide en Newtons (N).",
          },
          {
            id: "fis_new_5",
            type: "multiple_choice",
            concept: "Inercia al Frenar",
            question: "Según la explicación, ¿por qué te vas hacia adelante cuando un autobús frena repentinamente?",
            options: [
              "Porque la gravedad se apaga momentáneamente",
              "Por atracción magnética",
              "Por la inercia, tu cuerpo tiende a mantener la velocidad que llevaba",
              "Por la fuerza centrífuga de los motores",
            ],
            correctAnswer: "Por la inercia, tu cuerpo tiende a mantener la velocidad que llevaba",
            correctIndex: 2,
            explanation: "¿Por qué? La explicación indica textualmente que te vas hacia adelante por la inercia al frenar.",
          },
        ],
      },
    ],
  },
];
