import { type StudyQuestion } from "./study-game.functions";

export interface SubjectTopic {
  id: string;
  name: string;
  summary: string;
  explanation: string;
  keyPoints: string[];
  examples?: string[];
  presetQuestions: StudyQuestion[];
}

export interface SchoolSubject {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
  badgeColor: string;
  bgLight: string;
  borderColor: string;
  topics: SubjectTopic[];
}

export const SCHOOL_SUBJECTS: SchoolSubject[] = [
  // ==========================================
  // 1. MATEMÁTICAS
  // ==========================================
  {
    id: "matematicas",
    name: "Matemáticas",
    icon: "➗",
    description: "Números, álgebra, ecuaciones y problemas.",
    color: "text-blue-600 dark:text-blue-400",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    bgLight: "from-blue-500/10 to-indigo-500/5",
    borderColor: "border-blue-200 dark:border-blue-800/80",
    topics: [
      {
        id: "operaciones-basicas",
        name: "Operaciones básicas",
        summary: "Suma, resta, multiplicación, división y jerarquía de operaciones.",
        explanation:
          "Las operaciones básicas son el pilar de las matemáticas. Al resolver expresiones combinadas se sigue la jerarquía PEMDAS: primero paréntesis (), luego exponentes, multiplicaciones/divisiones de izquierda a derecha, y al final sumas/restas.",
        keyPoints: [
          "Jerarquía PEMDAS: Paréntesis → Potencias/Raíces → Multiplicación/División → Suma/Resta.",
          "Multiplicar por cero siempre resulta en 0 (a × 0 = 0).",
          "La división entre cero no está definida en los números reales.",
          "Leyes de los signos: Signos iguales dan positivo (+), signos diferentes dan negativo (-).",
        ],
        examples: ["4 + 3 × 2 = 4 + 6 = 10 (no 14)", "(-5) × (-3) = +15", "12 ÷ (2 + 4) = 12 ÷ 6 = 2"],
        presetQuestions: [
          {
            id: "mat_op_1",
            type: "multiple_choice",
            concept: "Jerarquía de Operaciones",
            question: "¿Cuál es el resultado correcto de la operación 5 + 4 × 3?",
            options: ["17", "27", "12", "20"],
            correctAnswer: "17",
            correctIndex: 0,
            explanation: "¿Por qué? Primero se calcula la multiplicación: 4 × 3 = 12, y luego se suma 5: 5 + 12 = 17.",
          },
          {
            id: "mat_op_2",
            type: "multiple_choice",
            concept: "Multiplicación con Signos",
            question: "¿Cuál es el resultado de (-6) × (-4)?",
            options: ["24", "-24", "-10", "10"],
            correctAnswer: "24",
            correctIndex: 0,
            explanation: "¿Por qué? Al multiplicar dos números con signo negativo, el resultado siempre es positivo: (- × - = +).",
          },
          {
            id: "mat_op_3",
            type: "fill_blank",
            concept: "Propiedad del Cero",
            question: "Cualquier número multiplicado por cero es igual a ________.",
            options: ["0", "1", "el mismo número", "infinito"],
            correctAnswer: "0",
            correctIndex: 0,
            explanation: "¿Por qué? El cero es el elemento absorbente de la multiplicación (a × 0 = 0).",
          },
          {
            id: "mat_op_4",
            type: "true_false",
            concept: "Uso de Paréntesis",
            question: "En una operación matemática, lo que está dentro de los paréntesis se resuelve antes que las sumas externas.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Los signos de agrupación tienen la máxima prioridad en la jerarquía de operaciones.",
          },
          {
            id: "mat_op_5",
            type: "multiple_choice",
            concept: "Operación de Multiplicación",
            question: "¿Cuál es el resultado de 8 × 7?",
            options: ["56", "54", "64", "48"],
            correctAnswer: "56",
            correctIndex: 0,
            explanation: "¿Por qué? 8 veces 7 es exactamente igual a 56.",
          },
        ],
      },
      {
        id: "fracciones",
        name: "Fracciones",
        summary: "Suma, resta, multiplicación, división y simplificación de fracciones.",
        explanation:
          "Una fracción representa partes de un todo. El numerador indica cuántas partes tomamos y el denominador el total. En multiplicación se multiplica en línea recta, y en división se multiplica cruzado.",
        keyPoints: [
          "Numerador (arriba) = partes que tomamos; Denominador (abajo) = total de partes.",
          "Multiplicación de fracciones: (a/b) × (c/d) = (a×c) / (b×d).",
          "División de fracciones: Se multiplica en cruz (a/b) ÷ (c/d) = (a×d) / (b×c).",
          "Suma con mismo denominador: Se suman numeradores y se mantiene el denominador.",
        ],
        examples: ["(2/3) × (4/5) = 8/15", "1/4 + 2/4 = 3/4", "(1/2) ÷ (1/3) = 3/2"],
        presetQuestions: [
          {
            id: "mat_frac_1",
            type: "multiple_choice",
            concept: "Multiplicación de Fracciones",
            question: "¿Cuál es el resultado de (2/5) × (3/4)?",
            options: ["6/20 (o 3/10)", "5/9", "8/15", "6/9"],
            correctAnswer: "6/20 (o 3/10)",
            correctIndex: 0,
            explanation: "¿Por qué? Numerador por numerador (2 × 3 = 6) y denominador por denominador (5 × 4 = 20), que simplificado es 3/10.",
          },
          {
            id: "mat_frac_2",
            type: "multiple_choice",
            concept: "Suma de Fracciones Homogéneas",
            question: "¿Cuánto es 3/8 + 2/8?",
            options: ["5/8", "5/16", "6/8", "6/16"],
            correctAnswer: "5/8",
            correctIndex: 0,
            explanation: "¿Por qué? Tienen el mismo denominador, por lo que se suman directamente los numeradores: 3 + 2 = 5/8.",
          },
          {
            id: "mat_frac_3",
            type: "true_false",
            concept: "Partes de una Fracción",
            question: "El denominador representa el total de partes iguales en que se dividió la unidad.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? El denominador indica la cantidad total de fracciones en que se divide el entero.",
          },
          {
            id: "mat_frac_4",
            type: "fill_blank",
            concept: "Fracción Equivalente",
            question: "La fracción 2/4 simplificada a su mínima expresión es igual a ________.",
            options: ["1/2", "1/4", "3/4", "2/2"],
            correctAnswer: "1/2",
            correctIndex: 0,
            explanation: "¿Por qué? Al dividir numerador y denominador entre 2 se obtiene 1/2.",
          },
          {
            id: "mat_frac_5",
            type: "multiple_choice",
            concept: "División de Fracciones",
            question: "¿Cuál es el resultado de (1/3) ÷ (2/5)?",
            options: ["5/6", "2/15", "3/10", "6/5"],
            correctAnswer: "5/6",
            correctIndex: 0,
            explanation: "¿Por qué? Se multiplica en cruz: 1 × 5 = 5 (arriba) y 3 × 2 = 6 (abajo), dando 5/6.",
          },
        ],
      },
      {
        id: "porcentajes",
        name: "Porcentajes",
        summary: "Cálculo de tanto por ciento, descuentos, aumentos e IVA.",
        explanation:
          "El porcentaje es una razón de base 100. Calcular el X% de una cantidad equivale a multiplicar por X y dividir entre 100, o multiplicar por el decimal correspondiente.",
        keyPoints: [
          "50% equivale a la mitad (× 0.5 o dividir entre 2).",
          "25% equivale a una cuarta parte (× 0.25 o dividir entre 4).",
          "10% equivale a recorrer el punto un lugar a la izquierda (× 0.1).",
          "Para aplicar un descuento del 20%, pagas el 80% del precio original.",
        ],
        examples: ["El 20% de 200 = 200 × 0.20 = 40", "El 10% de 350 = 35", "Un artículo de $100 con 15% de descuento cuesta $85"],
        presetQuestions: [
          {
            id: "mat_pct_1",
            type: "multiple_choice",
            concept: "Cálculo de Porcentaje",
            question: "¿Cuánto es el 20% de 150?",
            options: ["30", "20", "25", "15"],
            correctAnswer: "30",
            correctIndex: 0,
            explanation: "¿Por qué? 150 × 0.20 = 30 (o bien: el 10% es 15, así que el 20% es el doble, 30).",
          },
          {
            id: "mat_pct_2",
            type: "multiple_choice",
            concept: "Descuentos",
            question: "Una playera cuesta $200 y tiene el 50% de descuento. ¿Cuánto cuesta ahora?",
            options: ["$100", "$150", "$50", "$80"],
            correctAnswer: "$100",
            correctIndex: 0,
            explanation: "¿Por qué? El 50% representa exactamente la mitad del valor: $200 / 2 = $100.",
          },
          {
            id: "mat_pct_3",
            type: "true_false",
            concept: "Representación Decimal",
            question: "El 25% de un número equivale a multiplicarlo por 0.25.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? 25 / 100 = 0.25.",
          },
          {
            id: "mat_pct_4",
            type: "fill_blank",
            concept: "Porcentaje Base",
            question: "El 100% de cualquier número es igual a ________.",
            options: ["la totalidad del número", "cero", "el doble", "la mitad"],
            correctAnswer: "la totalidad del número",
            correctIndex: 0,
            explanation: "¿Por qué? El 100% representa el total completo del valor.",
          },
          {
            id: "mat_pct_5",
            type: "multiple_choice",
            concept: "Cálculo Rápido de 10%",
            question: "¿Cuánto es el 10% de 480?",
            options: ["48", "4.8", "480", "24"],
            correctAnswer: "48",
            correctIndex: 0,
            explanation: "¿Por qué? Para calcular el 10% simplemente se divide entre 10: 480 ÷ 10 = 48.",
          },
        ],
      },
      {
        id: "algebra",
        name: "Álgebra y Ecuaciones",
        summary: "Variables, términos semejantes y despeje de incógnitas (x).",
        explanation:
          "El álgebra utiliza letras para representar números desconocidos (incógnitas). En una ecuación, lo que está sumando pasa restando al otro lado, y lo que multiplica pasa dividiendo para dejar a la incógnita sola.",
        keyPoints: [
          "Términos semejantes: Solo se pueden sumar o restar si tienen la misma letra y exponente (ej. 3x + 2x = 5x).",
          "Regla de despeje: Pasa al otro lado con la operación inversa (+ pasa como -, × pasa como ÷).",
          "El objetivo al resolver una ecuación es hallar el valor numérico de la variable (x).",
        ],
        examples: ["Si x + 5 = 12 → x = 12 - 5 = 7", "Si 2x = 10 → x = 10 / 2 = 5", "3x + 4x = 7x"],
        presetQuestions: [
          {
            id: "mat_alg_1",
            type: "multiple_choice",
            concept: "Ecuaciones de Primer Grado",
            question: "En la ecuación 2x + 4 = 14, ¿cuál es el valor de x?",
            options: ["5", "7", "9", "4"],
            correctAnswer: "5",
            correctIndex: 0,
            explanation: "¿Por qué? Pasamos el 4 restando: 2x = 14 - 4 = 10. Luego pasamos el 2 dividiendo: x = 10 / 2 = 5.",
          },
          {
            id: "mat_alg_2",
            type: "multiple_choice",
            concept: "Términos Semejantes",
            question: "¿Cuál es el resultado de simplificar 4x + 7x - 2x?",
            options: ["9x", "13x", "9x²", "11x"],
            correctAnswer: "9x",
            correctIndex: 0,
            explanation: "¿Por qué? Sumamos y restamos los coeficientes: 4 + 7 = 11, y 11 - 2 = 9x.",
          },
          {
            id: "mat_alg_3",
            type: "true_false",
            concept: "Despeje de Ecuaciones",
            question: "Si un término está sumando en el lado izquierdo de una ecuación, pasa al lado derecho restando.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Para despejar una incógnita se aplican operaciones inversas.",
          },
          {
            id: "mat_alg_4",
            type: "fill_blank",
            concept: "Variable",
            question: "En la expresión 3x + 5, la letra 'x' recibe el nombre de ________.",
            options: ["variable o incógnita", "denominador", "constante fija", "exponente"],
            correctAnswer: "variable o incógnita",
            correctIndex: 0,
            explanation: "¿Por qué? La letra representa un valor variable o desconocido que se busca determinar.",
          },
          {
            id: "mat_alg_5",
            type: "multiple_choice",
            concept: "Ecuación Simple",
            question: "Si x - 8 = 12, ¿cuánto vale x?",
            options: ["20", "4", "96", "-4"],
            correctAnswer: "20",
            correctIndex: 0,
            explanation: "¿Por qué? El 8 pasa sumando: x = 12 + 8 = 20.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 2. QUÍMICA
  // ==========================================
  {
    id: "quimica",
    name: "Química",
    icon: "🧪",
    description: "Materia, elementos, reacciones y conceptos químicos.",
    color: "text-emerald-600 dark:text-emerald-400",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    bgLight: "from-emerald-500/10 to-teal-500/5",
    borderColor: "border-emerald-200 dark:border-emerald-800/80",
    topics: [
      {
        id: "materia-mezclas",
        name: "Materia, estados y mezclas",
        summary: "Estados de agregación, cambios de fase y mezclas homogéneas y heterogéneas.",
        explanation:
          "La materia es todo lo que ocupa un lugar en el espacio y tiene masa. Se presenta en estados sólido, líquido y gaseoso. Las mezclas homogéneas no permiten distinguir sus fases a simple vista (como el agua con sal), mientras que en las heterogéneas sí se distinguen (como agua con aceite).",
        keyPoints: [
          "Estados de la materia: Sólido (forma fija), Líquido (toma forma del recipiente), Gaseoso (se expande).",
          "Evaporación: Líquido → Gas; Condensación: Gas → Líquido; Fusión: Sólido → Líquido; Solidificación: Líquido → Sólido.",
          "Mezcla homogénea (disolución): Una sola fase uniforme (ej. aire, café colado).",
          "Mezcla heterogénea: Múltiples fases distinguibles (ej. ensalada, agua y aceite).",
        ],
        examples: ["El agua con sal bien disuelta es mezcla homogénea", "El granito y la arena con agua son heterogéneas"],
        presetQuestions: [
          {
            id: "qui_mat_1",
            type: "multiple_choice",
            concept: "Tipos de Mezclas",
            question: "¿Cuál de las siguientes es un ejemplo de mezcla homogénea?",
            options: ["Agua con sal completamente disuelta", "Agua con aceite", "Ensalada de frutas", "Arena con piedras"],
            correctAnswer: "Agua con sal completamente disuelta",
            correctIndex: 0,
            explanation: "¿Por qué? En una mezcla homogénea los componentes forman una sola fase visible uniforme.",
          },
          {
            id: "qui_mat_2",
            type: "multiple_choice",
            concept: "Cambios de Estado",
            question: "¿Cómo se llama el cambio de estado de sólido a líquido?",
            options: ["Fusión", "Evaporación", "Condensación", "Sublimación"],
            correctAnswer: "Fusión",
            correctIndex: 0,
            explanation: "¿Por qué? La fusión es el proceso físico mediante el cual un sólido absorbe calor y se transforma en líquido.",
          },
          {
            id: "qui_mat_3",
            type: "true_false",
            concept: "Gases",
            question: "Los gases tienen volumen y forma fijos.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Falso",
            correctIndex: 1,
            explanation: "¿Por qué? Los gases no tienen forma ni volumen fijos; se expanden para ocupar todo el espacio del recipiente que los contiene.",
          },
          {
            id: "qui_mat_4",
            type: "fill_blank",
            concept: "Condensación",
            question: "El paso del vapor de agua a agua líquida se conoce como ________.",
            options: ["condensación", "solidificación", "combustión", "fusión"],
            correctAnswer: "condensación",
            correctIndex: 0,
            explanation: "¿Por qué? La condensación ocurre cuando el gas pierde calor y se transforma en líquido.",
          },
          {
            id: "qui_mat_5",
            type: "multiple_choice",
            concept: "Mezcla Heterogénea",
            question: "¿Por qué el agua y el aceite forman una mezcla heterogénea?",
            options: [
              "Porque no se mezclan y se pueden distinguir dos fases claramente",
              "Porque forman una sola sustancia pura transparente",
              "Porque ambos son metales pesados",
              "Porque reaccionan produciendo fuego",
            ],
            correctAnswer: "Porque no se mezclan y se pueden distinguir dos fases claramente",
            correctIndex: 0,
            explanation: "¿Por qué? Debido a sus diferencias de polaridad y densidad, forman capas separadas distinguibles.",
          },
        ],
      },
      {
        id: "tabla-periodica",
        name: "Tabla periódica y átomos",
        summary: "Estructura atómica (protones, neutrones, electrones) y grupos de la tabla periódica.",
        explanation:
          "El átomo está formado por un núcleo con protones (+) y neutrones (neutros), rodeado por electrones (-). La tabla periódica organiza los elementos químicos según su número atómico creciente.",
        keyPoints: [
          "Número atómico (Z): Cantidad de protones que tiene un átomo en su núcleo.",
          "Cargas: Protones (+), Electrones (-), Neutrones (0).",
          "Símbolos esenciales: H (Hidrógeno), O (Oxígeno), C (Carbono), N (Nitrógeno), Fe (Hierro), Na (Sodio).",
          "Filas horizontales = Períodos; Columnas verticales = Grupos o Familias.",
        ],
        examples: ["El agua tiene fórmula H2O (2 átomos de Hidrógeno y 1 de Oxígeno)", "El gas helio es He"],
        presetQuestions: [
          {
            id: "qui_tab_1",
            type: "multiple_choice",
            concept: "Partículas Subatómicas",
            question: "¿Qué partículas con carga positiva se encuentran en el núcleo del átomo?",
            options: ["Los protones", "Los electrones", "Los neutrones", "Los fotones"],
            correctAnswer: "Los protones",
            correctIndex: 0,
            explanation: "¿Por qué? Los protones tienen carga eléctrica positiva y se ubican en el núcleo atómico.",
          },
          {
            id: "qui_tab_2",
            type: "multiple_choice",
            concept: "Símbolos Químicos",
            question: "¿Cuál es el símbolo químico del Oxígeno en la tabla periódica?",
            options: ["O", "Ox", "Om", "Og"],
            correctAnswer: "O",
            correctIndex: 0,
            explanation: "¿Por qué? El símbolo químico universal del elemento Oxígeno es la letra O mayúscula.",
          },
          {
            id: "qui_tab_3",
            type: "true_false",
            concept: "Carga del Electrón",
            question: "Los electrones orbitan alrededor del núcleo y poseen carga eléctrica negativa.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Los electrones son partículas subatómicas fundamentales con carga elemental negativa (-).",
          },
          {
            id: "qui_tab_4",
            type: "fill_blank",
            concept: "Número Atómico",
            question: "El número atómico de un elemento indica la cantidad de ________ en su núcleo.",
            options: ["protones", "electrones de valencia", "neutrones", "moléculas"],
            correctAnswer: "protones",
            correctIndex: 0,
            explanation: "¿Por qué? El número atómico (Z) define la identidad de cada elemento por su número de protones.",
          },
          {
            id: "qui_tab_5",
            type: "multiple_choice",
            concept: "Fórmula del Agua",
            question: "¿Cuántos átomos de hidrógeno tiene una molécula de agua (H₂O)?",
            options: ["2", "1", "3", "0"],
            correctAnswer: "2",
            correctIndex: 0,
            explanation: "¿Por qué? El subíndice 2 indica 2 átomos de hidrógeno unidos a 1 átomo de oxígeno.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 3. INGLÉS
  // ==========================================
  {
    id: "ingles",
    name: "Inglés",
    icon: "🇬🇧",
    description: "Gramática, vocabulario y comprensión.",
    color: "text-rose-600 dark:text-rose-400",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    bgLight: "from-rose-500/10 to-red-500/5",
    borderColor: "border-rose-200 dark:border-rose-800/80",
    topics: [
      {
        id: "verb-to-be",
        name: "Verb To Be & Pronouns",
        summary: "Uso de am, is, are y pronombres personales (I, you, he, she, it, we, they).",
        explanation:
          "El verbo 'to be' significa 'ser' o 'estar'. Se conjuga como: I am, You are, He is, She is, It is, We are, They are.",
        keyPoints: [
          "I → am (I am a student / Yo soy estudiante)",
          "He / She / It → is (She is happy / Ella está feliz)",
          "You / We / They → are (We are friends / Nosotros somos amigos)",
          "Negación: am not, is not (isn't), are not (aren't).",
        ],
        examples: ["He is my brother", "They are at school", "I am studying English"],
        presetQuestions: [
          {
            id: "eng_be_1",
            type: "multiple_choice",
            concept: "Conjugación Verb To Be",
            question: "Completa la oración: 'She ________ my best friend.'",
            options: ["is", "are", "am", "be"],
            correctAnswer: "is",
            correctIndex: 0,
            explanation: "¿Por qué? Para la tercera persona singular (he, she, it) se usa la forma 'is'.",
          },
          {
            id: "eng_be_2",
            type: "multiple_choice",
            concept: "Plural Verb To Be",
            question: "Completa la oración: 'They ________ playing soccer in the park.'",
            options: ["are", "is", "am", "was"],
            correctAnswer: "are",
            correctIndex: 0,
            explanation: "¿Por qué? Con el pronombre 'they' (ellos) se utiliza la forma plural 'are'.",
          },
          {
            id: "eng_be_3",
            type: "true_false",
            concept: "Primera Persona",
            question: "La forma correcta para decir 'Yo soy / Yo estoy' en inglés es 'I am'.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? El pronombre 'I' se conjuga exclusivamente con 'am' en presente simple.",
          },
          {
            id: "eng_be_4",
            type: "fill_blank",
            concept: "Pronombre de Cosas/Animales",
            question: "En inglés, el pronombre utilizado para referirse a un objeto o animal es ________.",
            options: ["it", "he", "they", "we"],
            correctAnswer: "it",
            correctIndex: 0,
            explanation: "¿Por qué? 'It' es el pronombre neutro singular para cosas, animales o conceptos.",
          },
          {
            id: "eng_be_5",
            type: "multiple_choice",
            concept: "Forma Negativa",
            question: "¿Cuál es la contracción negativa correcta de 'is not'?",
            options: ["isn't", "aren't", "amn't", "don't"],
            correctAnswer: "isn't",
            correctIndex: 0,
            explanation: "¿Por qué? 'Is not' se contrae como 'isn't'.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 4. HISTORIA
  // ==========================================
  {
    id: "historia",
    name: "Historia",
    icon: "📜",
    description: "Civilizaciones, acontecimientos y personajes históricos.",
    color: "text-amber-700 dark:text-amber-400",
    badgeColor: "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/20",
    bgLight: "from-amber-500/10 to-yellow-500/5",
    borderColor: "border-amber-200 dark:border-amber-800/80",
    topics: [
      {
        id: "civilizaciones-antiguas",
        name: "Civilizaciones antiguas",
        summary: "Mesopotamia, Egipto, Grecia y Roma.",
        explanation:
          "Las primeras civilizaciones se asentaron cerca de grandes ríos. Mesopotamia creó la escritura cuneiforme; Egipto construyó pirámides junto al Nilo; Grecia aportó la democracia y la filosofía; y Roma el derecho y la ingeniería de calzadas y acueductos.",
        keyPoints: [
          "Mesopotamia: 'Tierra entre dos ríos' (Tigris y Éufrates), inventó la escritura cuneiforme.",
          "Egipto: Floreció en el río Nilo; gobernado por faraones con religión politeísta.",
          "Grecia: Cuna de la democracia (Atenas), los Juegos Olímpicos y la filosofía clásica.",
          "Roma: Gran imperio mediterráneo; legado del Derecho romano y el latín.",
        ],
        examples: ["El Código de Hammurabi es una de las leyes más antiguas de Mesopotamia", "El Coliseo fue construido en Roma"],
        presetQuestions: [
          {
            id: "his_civ_1",
            type: "multiple_choice",
            concept: "Mesopotamia",
            question: "¿Qué ríos alimentaban los valles de la antigua Mesopotamia?",
            options: ["Tigris y Éufrates", "Nilo y Amazonas", "Ganges e Indo", "Rin y Danubio"],
            correctAnswer: "Tigris y Éufrates",
            correctIndex: 0,
            explanation: "¿Por qué? Mesopotamia significa literalmente 'tierra entre dos ríos' en referencia al Tigris y Éufrates.",
          },
          {
            id: "his_civ_2",
            type: "multiple_choice",
            concept: "Aporte Griego",
            question: "¿Qué sistema de gobierno nació en la antigua ciudad griega de Atenas?",
            options: ["La democracia", "La monarquía absoluta", "El feudalismo", "La dictadura militar"],
            correctAnswer: "La democracia",
            correctIndex: 0,
            explanation: "¿Por qué? En Atenas los ciudadanos participaban en asambleas para votar y tomar decisiones (demos = pueblo, kratos = poder).",
          },
          {
            id: "his_civ_3",
            type: "true_false",
            concept: "Egipto y el Nilo",
            question: "La civilización egipcia dependía de las crecidas del río Nilo para fertilizar sus cultivos.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? El Nilo dejaba una capa de limo fértil esencial para la agricultura en el desierto.",
          },
          {
            id: "his_civ_4",
            type: "fill_blank",
            concept: "Escritura Antigua",
            question: "La escritura en forma de cuñas desarrollada en Mesopotamia se llama ________.",
            options: ["cuneiforme", "jeroglífica", "alfabeto latino", "griega"],
            correctAnswer: "cuneiforme",
            correctIndex: 0,
            explanation: "¿Por qué? Se tallaba con estiletes en tablillas de arcilla blanda.",
          },
          {
            id: "his_civ_5",
            type: "multiple_choice",
            concept: "Legado Romano",
            question: "¿Cuál fue uno de los principales legados de Roma a la sociedad moderna?",
            options: ["El Derecho y las bases de las leyes actuales", "La brújula magnética", "La invención del papel", "El ábaco"],
            correctAnswer: "El Derecho y las bases de las leyes actuales",
            correctIndex: 0,
            explanation: "¿Por qué? El Derecho romano sentó las bases jurídicas del mundo occidental.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 5. BIOLOGÍA
  // ==========================================
  {
    id: "biologia",
    name: "Biología",
    icon: "🧬",
    description: "Seres vivos, células, genética y sistemas.",
    color: "text-emerald-700 dark:text-emerald-400",
    badgeColor: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/20",
    bgLight: "from-emerald-500/10 to-green-500/5",
    borderColor: "border-emerald-200 dark:border-emerald-800/80",
    topics: [
      {
        id: "la-celula",
        name: "La célula y organelos",
        summary: "Estructura celular, procariotas, eucariotas, mitocondria y fotosíntesis.",
        explanation:
          "La célula es la unidad básica de todos los seres vivos. Las células eucariotas tienen núcleo definido (animales y vegetales), mientras que las procariotas no (bacterias). Los organelos como la mitocondria producen energía y los cloroplastos realizan la fotosíntesis.",
        keyPoints: [
          "Célula = Unidad anatómica, funcional y de origen de la vida.",
          "Procariotas: Sin núcleo delimitado; Eucariotas: Con núcleo protegido por membrana.",
          "Mitocondria: Respiración celular y síntesis de ATP (energía).",
          "Cloroplastos y pared celular: Exclusivos de las células vegetales.",
        ],
        examples: ["Las bacterias son organismos unicelulares procariotas", "Las plantas y animales son eucariotas"],
        presetQuestions: [
          {
            id: "bio_cel_1",
            type: "multiple_choice",
            concept: "Función de la Mitocondria",
            question: "¿Cuál es la función principal de la mitocondria?",
            options: [
              "Generar energía (ATP) a través de la respiración celular",
              "Sintetizar la pared de celulosa",
              "Almacenar el material genético de los virus",
              "Realizar la fotosíntesis con luz solar",
            ],
            correctAnswer: "Generar energía (ATP) a través de la respiración celular",
            correctIndex: 0,
            explanation: "¿Por qué? La mitocondria transforma nutrientes y oxígeno en ATP para alimentar a la célula.",
          },
          {
            id: "bio_cel_2",
            type: "multiple_choice",
            concept: "Célula Vegetal",
            question: "¿Qué estructura otorga rigidez y soporte exclusivo a las células vegetales?",
            options: ["La pared celular de celulosa", "La membrana plasmática", "El citoplasma", "El lisosoma"],
            correctAnswer: "La pared celular de celulosa",
            correctIndex: 0,
            explanation: "¿Por qué? La pared celular vegetal protege la célula y le brinda soporte mecánico.",
          },
          {
            id: "bio_cel_3",
            type: "true_false",
            concept: "Teoría Celular",
            question: "Todos los seres vivos están formados por una o más células.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Es el postulado central de la biología celular.",
          },
          {
            id: "bio_cel_4",
            type: "fill_blank",
            concept: "Centro de Control",
            question: "El organelo que alberga el ADN y dirige la actividad celular es el ________.",
            options: ["núcleo", "ribosoma", "retículo", "flagelo"],
            correctAnswer: "núcleo",
            correctIndex: 0,
            explanation: "¿Por qué? El núcleo contiene la información genética de la célula.",
          },
          {
            id: "bio_cel_5",
            type: "multiple_choice",
            concept: "Fotosíntesis",
            question: "¿En qué organelo vegetal ocurre el proceso de fotosíntesis?",
            options: ["En los cloroplastos", "En las mitocondrias", "En el aparato de Golgi", "En los centriolos"],
            correctAnswer: "En los cloroplastos",
            correctIndex: 0,
            explanation: "¿Por qué? Los cloroplastos capturan luz mediante la clorofila para producir glucosa y oxígeno.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 6. ESPAÑOL
  // ==========================================
  {
    id: "espanol",
    name: "Español",
    icon: "📖",
    description: "Gramática, lectura, literatura y escritura.",
    color: "text-purple-600 dark:text-purple-400",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    bgLight: "from-purple-500/10 to-indigo-500/5",
    borderColor: "border-purple-200 dark:border-purple-800/80",
    topics: [
      {
        id: "ortografia-acentuacion",
        name: "Acentuación y ortografía",
        summary: "Palabras agudas, graves, esdrújulas y reglas de tilde.",
        explanation:
          "Según la sílaba donde recae la fuerza de voz (sílaba tónica), las palabras se clasifican en: Agudas (última sílaba), Graves (penúltima), Esdrújulas (antepenúltima) y Sobreesdrújulas (anterior a la antepenúltima).",
        keyPoints: [
          "Agudas: Llevan tilde si terminan en N, S o Vocal (ej. can-ción, ca-fé, so-fá).",
          "Graves: Llevan tilde si NO terminan en N, S o Vocal (ej. ár-bol, lá-piz, fá-cil).",
          "Esdrújulas: SIEMPRE llevan tilde (ej. mú-si-ca, cé-lu-la, plá-ta-no).",
          "Sobreesdrújulas: SIEMPRE llevan tilde (ej. có-me-te-lo, dí-ga-se-lo).",
        ],
        examples: ["Canción (aguda con tilde)", "Árbol (grave con tilde)", "Música (esdrújula)"],
        presetQuestions: [
          {
            id: "esp_ort_1",
            type: "multiple_choice",
            concept: "Palabras Esdrújulas",
            question: "¿Cuál de las siguientes palabras es esdrújula?",
            options: ["Música", "Canción", "Reloj", "Papel"],
            correctAnswer: "Música",
            correctIndex: 0,
            explanation: "¿Por qué? Lleva el acento en la antepenúltima sílaba (MÚ-si-ca) y todas las esdrújulas se acentúan.",
          },
          {
            id: "esp_ort_2",
            type: "multiple_choice",
            concept: "Regla de Palabras Agudas",
            question: "¿Cuándo llevan tilde las palabras agudas?",
            options: [
              "Cuando terminan en N, S o Vocal",
              "Cuando terminan en cualquier consonante excepto N o S",
              "Siempre, sin excepción",
              "Nunca llevan tilde",
            ],
            correctAnswer: "Cuando terminan en N, S o Vocal",
            correctIndex: 0,
            explanation: "¿Por qué? Es la regla fundamental de acentuación de las palabras agudas.",
          },
          {
            id: "esp_ort_3",
            type: "true_false",
            concept: "Palabras Graves",
            question: "La palabra 'árbol' es grave y lleva tilde porque termina en consonante 'L' (distinta de N o S).",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Las palabras graves se acentúan ortográficamente cuando no terminan en N, S o vocal.",
          },
          {
            id: "esp_ort_4",
            type: "fill_blank",
            concept: "Sílaba Tónica",
            question: "La sílaba que se pronuncia con mayor intensidad o fuerza en una palabra es la sílaba ________.",
            options: ["tónica", "átona", "diptongo", "hiato"],
            correctAnswer: "tónica",
            correctIndex: 0,
            explanation: "¿Por qué? La sílaba tónica concentra el acento fonético de la palabra.",
          },
          {
            id: "esp_ort_5",
            type: "multiple_choice",
            concept: "Clasificación de Palabras",
            question: "¿Qué tipo de palabra es 'corazón'?",
            options: ["Aguda", "Grave", "Esdrújula", "Sobreesdrújula"],
            correctAnswer: "Aguda",
            correctIndex: 0,
            explanation: "¿Por qué? Su sílaba tónica es la última (co-ra-ZÓN) y termina en 'N'.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 7. GEOGRAFÍA
  // ==========================================
  {
    id: "geografia",
    name: "Geografía",
    icon: "🌎",
    description: "Países, mapas, clima y territorio.",
    color: "text-cyan-600 dark:text-cyan-400",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    bgLight: "from-cyan-500/10 to-sky-500/5",
    borderColor: "border-cyan-200 dark:border-cyan-800/80",
    topics: [
      {
        id: "continentes-oceanos",
        name: "Continentes y océanos",
        summary: "Los 5 continentes y los principales océanos del planeta Tierra.",
        explanation:
          "La superficie terrestre está cubierta en un 70% por agua (océanos) y un 30% por masas continentales. Los cinco continentes habitados son América, Europa, Asia, África y Oceanía (más la Antártida), y el Océano Pacífico es el más grande del mundo.",
        keyPoints: [
          "Océano Pacífico: El más grande y profundo del planeta.",
          "Asia: El continente con mayor extensión territorial y población del mundo.",
          "Línea del Ecuador: Divide a la Tierra en hemisferio Norte y hemisferio Sur.",
          "Meridiano de Greenwich: Divide al planeta en hemisferio Este y Oeste.",
        ],
        examples: ["El monte Everest está en Asia", "El río Amazonas fluye por América del Sur"],
        presetQuestions: [
          {
            id: "geo_con_1",
            type: "multiple_choice",
            concept: "Océanos del Mundo",
            question: "¿Cuál es el océano más grande del planeta Tierra?",
            options: ["Océano Pacífico", "Océano Atlántico", "Océano Índico", "Océano Ártico"],
            correctAnswer: "Océano Pacífico",
            correctIndex: 0,
            explanation: "¿Por qué? El Océano Pacífico cubre más de un tercio de la superficie de la Tierra.",
          },
          {
            id: "geo_con_2",
            type: "multiple_choice",
            concept: "Líneas Imaginarias",
            question: "¿Qué línea imaginaria divide la Tierra en Hemisferio Norte y Hemisferio Sur?",
            options: ["El Ecuador", "El Meridiano de Greenwich", "El Trópico de Cáncer", "El Círculo Polar"],
            correctAnswer: "El Ecuador",
            correctIndex: 0,
            explanation: "¿Por qué? El paralelo 0° o Ecuador divide simétricamente al globo en Norte y Sur.",
          },
          {
            id: "geo_con_3",
            type: "true_false",
            concept: "Continente Más Extenso",
            question: "Asia es el continente más grande y poblado del mundo.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Asia concentra más del 60% de la población mundial y la mayor superficie territorial.",
          },
          {
            id: "geo_con_4",
            type: "fill_blank",
            concept: "Proporción de Agua",
            question: "Aproximadamente el ________% de la superficie de la Tierra está cubierta por agua.",
            options: ["70", "30", "50", "95"],
            correctAnswer: "70",
            correctIndex: 0,
            explanation: "¿Por qué? Más de dos tercios del planeta están formados por mares y océanos.",
          },
          {
            id: "geo_con_5",
            type: "multiple_choice",
            concept: "Montaña Más Alta",
            question: "¿En qué cordillera y continente se encuentra el monte Everest?",
            options: ["El Himalaya (Asia)", "Los Andes (América)", "Los Alpes (Europa)", "Rocosas (América)"],
            correctAnswer: "El Himalaya (Asia)",
            correctIndex: 0,
            explanation: "¿Por qué? El Everest (8,848 m) se ubica en la cordillera del Himalaya en Asia.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 8. INFORMÁTICA / TECNOLOGÍA
  // ==========================================
  {
    id: "informatica",
    name: "Informática",
    icon: "💻",
    description: "Tecnología, programación y conceptos digitales.",
    color: "text-indigo-600 dark:text-indigo-400",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    bgLight: "from-indigo-500/10 to-violet-500/5",
    borderColor: "border-indigo-200 dark:border-indigo-800/80",
    topics: [
      {
        id: "hardware-software",
        name: "Hardware y software",
        summary: "Componentes físicos, programas, sistemas operativos y redes.",
        explanation:
          "El Hardware es la parte física y tangible de la computadora (procesador, memoria RAM, disco duro, pantalla, teclado). El Software son los programas y aplicaciones lógicas (sistemas operativos, navegadores, videojuegos).",
        keyPoints: [
          "Hardware: Componentes físicos que se pueden tocar (CPU, RAM, Disco, Monitor).",
          "Software: Instrucciones y programas lógicos (Windows, macOS, Linux, navegadores).",
          "CPU (Procesador): El 'cerebro' que ejecuta las instrucciones y cálculos.",
          "Memoria RAM: Memoria temporal rápida de trabajo (se borra al apagar el equipo).",
        ],
        examples: ["El teclado es hardware de entrada", "Un navegador web es software"],
        presetQuestions: [
          {
            id: "inf_hw_1",
            type: "multiple_choice",
            concept: "Definición de Hardware",
            question: "¿Cuál de los siguientes es un ejemplo de hardware?",
            options: ["El teclado físico", "El sistema operativo Windows", "Un videojuego digital", "Un archivo PDF"],
            correctAnswer: "El teclado físico",
            correctIndex: 0,
            explanation: "¿Por qué? El hardware corresponde a todas las partes físicas y componentes electrónicos tangibles.",
          },
          {
            id: "inf_hw_2",
            type: "multiple_choice",
            concept: "Función del Procesador (CPU)",
            question: "¿Cuál es el componente conocido como el 'cerebro' de la computadora?",
            options: ["La CPU (Procesador)", "La fuente de poder", "El ratón", "El gabinete"],
            correctAnswer: "La CPU (Procesador)",
            correctIndex: 0,
            explanation: "¿Por qué? La Unidad Central de Procesamiento (CPU) ejecuta todas las operaciones lógicas y matemáticas del sistema.",
          },
          {
            id: "inf_hw_3",
            type: "true_false",
            concept: "Memoria RAM",
            question: "La memoria RAM es una memoria temporal que pierde sus datos cuando la computadora se apaga.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? La memoria RAM es volátil y sirve únicamente para mantener abiertos los programas en uso actual.",
          },
          {
            id: "inf_hw_4",
            type: "fill_blank",
            concept: "Software del Sistema",
            question: "Windows, macOS y Linux son ejemplos de ________.",
            options: ["sistemas operativos", "dispositivos de almacenamiento", "chips de memoria", "antenas de red"],
            correctAnswer: "sistemas operativos",
            correctIndex: 0,
            explanation: "¿Por qué? Son el software principal que administra los recursos del hardware y permite usar las aplicaciones.",
          },
          {
            id: "inf_hw_5",
            type: "multiple_choice",
            concept: "Unidades de Almacenamiento",
            question: "¿Cuántos Megabytes (MB) equivalen aproximadamente a 1 Gigabyte (GB)?",
            options: ["1,024 MB", "100 MB", "10 MB", "1,000,000 MB"],
            correctAnswer: "1,024 MB",
            correctIndex: 0,
            explanation: "¿Por qué? En el sistema binario digital, 1 GB = 1,024 MB.",
          },
        ],
      },
    ],
  },

  // ==========================================
  // 9. FÍSICA
  // ==========================================
  {
    id: "fisica",
    name: "Física",
    icon: "⚡",
    description: "Movimiento, fuerza, energía y materia.",
    color: "text-amber-600 dark:text-amber-400",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    bgLight: "from-amber-500/10 to-orange-500/5",
    borderColor: "border-amber-200 dark:border-amber-800/80",
    topics: [
      {
        id: "leyes-newton-fisica",
        name: "Leyes de Newton y movimiento",
        summary: "Inercia, fuerza y masa (F = m·a), y acción-reacción.",
        explanation:
          "La física clásica describe cómo se mueven los cuerpos mediante las 3 leyes de Newton: 1ª Ley de Inercia, 2ª Ley Fundamental (Fuerza = masa × aceleración) y 3ª Ley de Acción y Reacción.",
        keyPoints: [
          "1ª Ley (Inercia): Los objetos mantienen su reposo o movimiento rectilíneo si no actúa una fuerza neta.",
          "2ª Ley (Fuerza): F = m × a (Fuerza en Newtons = masa en kg × aceleración en m/s²).",
          "3ª Ley (Acción y Reacción): A toda acción le corresponde una reacción opuesta de igual magnitud.",
          "Velocidad: Distancia dividida entre el tiempo (v = d / t).",
        ],
        examples: ["F = (5 kg) × (2 m/s²) = 10 N", "Si recorres 100 m en 10 s, tu velocidad es v = 10 m/s"],
        presetQuestions: [
          {
            id: "fis_new_1",
            type: "multiple_choice",
            concept: "Fórmula de Fuerza",
            question: "¿Cuál es la fórmula matemática de la Segunda Ley de Newton?",
            options: ["F = m · a", "E = m · c²", "v = d / t", "W = F / d"],
            correctAnswer: "F = m · a",
            correctIndex: 0,
            explanation: "¿Por qué? La fuerza es directamente proporcional a la masa del cuerpo y la aceleración producida (F = m·a).",
          },
          {
            id: "fis_new_2",
            type: "multiple_choice",
            concept: "Cálculo de Velocidad",
            question: "Un automóvil recorre 120 metros en 6 segundos. ¿Cuál es su velocidad constante?",
            options: ["20 m/s", "720 m/s", "12 m/s", "60 m/s"],
            correctAnswer: "20 m/s",
            correctIndex: 0,
            explanation: "¿Por qué? La velocidad se calcula con v = d / t: 120 m / 6 s = 20 m/s.",
          },
          {
            id: "fis_new_3",
            type: "true_false",
            concept: "Tercera Ley de Newton",
            question: "Cuando un cohete expulsa gases hacia abajo, el cohete es impulsado hacia arriba por la fuerza de reacción.",
            options: ["Verdadero", "Falso"],
            correctAnswer: "Verdadero",
            correctIndex: 0,
            explanation: "¿Por qué? Es una demostración directa del principio de acción y reacción (Tercera Ley de Newton).",
          },
          {
            id: "fis_new_4",
            type: "fill_blank",
            concept: "Unidad de Fuerza",
            question: "En el Sistema Internacional, la unidad de medida de la fuerza es el ________.",
            options: ["Newton (N)", "Joule (J)", "Watt (W)", "Pascal (Pa)"],
            correctAnswer: "Newton (N)",
            correctIndex: 0,
            explanation: "¿Por qué? La fuerza se mide en Newtons (1 N = 1 kg·m/s²).",
          },
          {
            id: "fis_new_5",
            type: "multiple_choice",
            concept: "Inercia",
            question: "¿Por qué te vas hacia adelante cuando un autobús frena repentinamente?",
            options: [
              "Por la inercia, tu cuerpo tiende a mantener la velocidad que llevaba",
              "Porque la gravedad se apaga momentáneamente",
              "Por la fuerza centrífuga de los motores",
              "Por atracción magnética",
            ],
            correctAnswer: "Por la inercia, tu cuerpo tiende a mantener la velocidad que llevaba",
            correctIndex: 0,
            explanation: "¿Por qué? La Primera Ley (Inercia) establece que un cuerpo tiende a continuar su movimiento a menos que una fuerza lo detenga.",
          },
        ],
      },
    ],
  },
];
